// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "@prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: process.env["DATABASE_URL"] ?? (() => {
      throw new Error("DATABASE_URL environment variable is not set");
    })(),
    directUrl: process.env["DIRECT_URL"] ?? (() => {
      throw new Error("DIRECT_URL environment variable is not set");
    })(),
  },
});
